// Auto-generated client visit image requires
const CLIENT_VISIT_IMAGES = {
  'Brazil Dalneem': [
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_01.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_02.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_03.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_04.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_05.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_06.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_07.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_08.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_09.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_10.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_11.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_12.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_13.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_14.jpeg'),
    require('../assets/images/ClientVisit/brazil_dalneem/brazil_dalneem_15.jpeg'),
  ],
  'France Berkem': [
    require('../assets/images/ClientVisit/france_berkem/france_berkem_01.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_02.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_03.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_04.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_05.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_06.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_07.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_08.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_09.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_10.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_11.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_12.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_13.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_14.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_15.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_16.jpeg'),
    require('../assets/images/ClientVisit/france_berkem/france_berkem_17.jpeg'),
  ],
  'Germany Greenshof': [
    require('../assets/images/ClientVisit/germany_greenshof/germany_greenshof_01.jpeg'),
    require('../assets/images/ClientVisit/germany_greenshof/germany_greenshof_02.jpeg'),
    require('../assets/images/ClientVisit/germany_greenshof/germany_greenshof_03.jpeg'),
    require('../assets/images/ClientVisit/germany_greenshof/germany_greenshof_04.jpeg'),
    require('../assets/images/ClientVisit/germany_greenshof/germany_greenshof_05.jpeg'),
  ],
  'Glover Ghana': [
    require('../assets/images/ClientVisit/glover_ghana/glover_ghana_01.jpeg'),
    require('../assets/images/ClientVisit/glover_ghana/glover_ghana_02.jpeg'),
    require('../assets/images/ClientVisit/glover_ghana/glover_ghana_03.jpeg'),
  ],
  'Kenya Osho': [
    require('../assets/images/ClientVisit/kenya_osho/kenya_osho_01.jpeg'),
    require('../assets/images/ClientVisit/kenya_osho/kenya_osho_02.jpeg'),
    require('../assets/images/ClientVisit/kenya_osho/kenya_osho_03.jpeg'),
    require('../assets/images/ClientVisit/kenya_osho/kenya_osho_04.jpeg'),
    require('../assets/images/ClientVisit/kenya_osho/kenya_osho_05.jpeg'),
  ],
  'Kim South Korea': [
    require('../assets/images/ClientVisit/kim_south_korea/kim_south_korea_01.jpg'),
    require('../assets/images/ClientVisit/kim_south_korea/kim_south_korea_02.jpg'),
    require('../assets/images/ClientVisit/kim_south_korea/kim_south_korea_03.jpg'),
  ],
  'Omex UK': [
    require('../assets/images/ClientVisit/omex_uk/omex_uk_01.jpeg'),
    require('../assets/images/ClientVisit/omex_uk/omex_uk_02.jpeg'),
    require('../assets/images/ClientVisit/omex_uk/omex_uk_03.jpeg'),
    require('../assets/images/ClientVisit/omex_uk/omex_uk_04.jpeg'),
    require('../assets/images/ClientVisit/omex_uk/omex_uk_05.jpeg'),
    require('../assets/images/ClientVisit/omex_uk/omex_uk_06.jpeg'),
    require('../assets/images/ClientVisit/omex_uk/omex_uk_07.jpeg'),
    require('../assets/images/ClientVisit/omex_uk/omex_uk_08.jpeg'),
    require('../assets/images/ClientVisit/omex_uk/omex_uk_09.jpeg'),
    require('../assets/images/ClientVisit/omex_uk/omex_uk_10.jpeg'),
  ],
  'SemiAgro Ecuador': [
    require('../assets/images/ClientVisit/semiagro_ecuador/semiagro_ecuador_01.jpeg'),
    require('../assets/images/ClientVisit/semiagro_ecuador/semiagro_ecuador_02.jpeg'),
    require('../assets/images/ClientVisit/semiagro_ecuador/semiagro_ecuador_03.jpeg'),
    require('../assets/images/ClientVisit/semiagro_ecuador/semiagro_ecuador_04.jpeg'),
    require('../assets/images/ClientVisit/semiagro_ecuador/semiagro_ecuador_05.jpeg'),
    require('../assets/images/ClientVisit/semiagro_ecuador/semiagro_ecuador_06.jpeg'),
    require('../assets/images/ClientVisit/semiagro_ecuador/semiagro_ecuador_07.jpeg'),
    require('../assets/images/ClientVisit/semiagro_ecuador/semiagro_ecuador_08.jpeg'),
    require('../assets/images/ClientVisit/semiagro_ecuador/semiagro_ecuador_09.jpeg'),
    require('../assets/images/ClientVisit/semiagro_ecuador/semiagro_ecuador_10.jpeg'),
    require('../assets/images/ClientVisit/semiagro_ecuador/semiagro_ecuador_11.jpeg'),
  ],
  'Techno Valley Egypt': [
    require('../assets/images/ClientVisit/techno_valley_egypt/techno_valley_egypt_01.jpeg'),
    require('../assets/images/ClientVisit/techno_valley_egypt/techno_valley_egypt_02.jpeg'),
    require('../assets/images/ClientVisit/techno_valley_egypt/techno_valley_egypt_03.jpeg'),
    require('../assets/images/ClientVisit/techno_valley_egypt/techno_valley_egypt_04.jpeg'),
    require('../assets/images/ClientVisit/techno_valley_egypt/techno_valley_egypt_05.jpeg'),
    require('../assets/images/ClientVisit/techno_valley_egypt/techno_valley_egypt_06.jpeg'),
  ],
  'Turkey': [
    require('../assets/images/ClientVisit/turkey/turkey_01.jpeg'),
  ],
};

export default CLIENT_VISIT_IMAGES;
